engines:
  rubocop:
    enabled: false
    #checks:
    #	Rubocop/Metrics/ClassLength:
    #  	enabled: false
  golint:
   	enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
  	enabled: true
    config:
    	languages:
      - typescript
      	#mass_threshold: 30
      - javascript
exclude_paths:
- */typings/*
